export const FETCH_LIVE = 'FETCH_LIVE'
export const PUSH_TO_GOALING_QUEUE = 'PUSH_TO_GOALING_QUEUE'
export const SHIFT_FROM_GOALING_QUEUE = 'SHIFT_FROM_GOALING_QUEUE'

export const FETCH_MATCH_DETAIL = 'FETCH_MATCH_DETAIL'
export const FETCH_LOTTERY_WITH_EXPERT = 'FETCH_LOTTERY_WITH_EXPERT'
export const FETCH_MATCH_COMMENTS = 'FETCH_MATCH_COMMENTS'